# Generated by Django 3.2.7 on 2021-09-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='owner',
        ),
    ]
